Update README.md
codecov/example-node pull request #50
Opened 2021-07-10 18:07 UTC by rlam3

Update codecov with github actions link

2021-07-24 02:53 UTC, tnir requested changes

2021-07-24 02:53 UTC, tnir commented on README.md
> +### [Github Actions](https://github.com/codecov/codecov-action)
```suggestion
### [GitHub Actions](https://github.com/codecov/codecov-action)
```

2021-07-24 02:56 UTC, tnir requested changes

2021-07-24 02:56 UTC, tnir commented on README.md
> +  uses: codecov/codecov-action@v1
```suggestion
  uses: codecov/codecov-action@v2
```
See https://about.codecov.io/blog/introducing-codecovs-new-uploader/ for detail.

2021-07-26 19:21 UTC, thomasrockhu commented
Thanks all!

2021-07-26 19:21 UTC, thomasrockhu approved these changes

2021-07-26 19:21 UTC, merged